name: Example Workflow
on: push
jobs:
  Test:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-git-mirror-1gb
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions
